error_code = {
  "E100": "Missing field user_name",
  "E101": "Missing field role",
  "E102": "Missing field name",
  "E103": "Missing field organize",
  "E104": "Missing field password",
  "E105": "Password must at least 6 characters",
  "E106": "you need user name and password to sign in",
  "E107": "User name or password incorrect",
  "E108": "JWT not found or expried",
  "E109": "Permission denied",
  "E110": "Body is required",
  "E111": "Account is disable. Please contact admin to enable",
  "E112": "Missing field adrress",
  "E113": "Missing field id_number",
  "E114": "Missing field image",
  "E115": "Missing field real_image",
  "E116": "Face not found in image",
  "E117": "Missing field percent",
  "E118": "Missing field crime_id",
  "E404": "Not found"
}