"""empty message

Revision ID: 289cd9ecaab0
Revises: 07b66faedc30
Create Date: 2020-12-29 14:56:05.777739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289cd9ecaab0'
down_revision = '07b66faedc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
