"""empty message

Revision ID: 809445e41b69
Revises: cb79100da224
Create Date: 2021-04-13 16:26:42.122580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809445e41b69'
down_revision = 'cb79100da224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'percent',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'percent',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
