"""empty message

Revision ID: cb79100da224
Revises: 345283f2876c
Create Date: 2021-01-23 16:58:03.091201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb79100da224'
down_revision = '345283f2876c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('face_image', sa.String(length=1500000), nullable=False))
    op.add_column('logs', sa.Column('image', sa.String(length=1500000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'image')
    op.drop_column('logs', 'face_image')
    # ### end Alembic commands ###
