"""empty message

Revision ID: cbf91883bb6a
Revises: 3ddc6b7e526f
Create Date: 2021-01-11 10:49:53.338948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf91883bb6a'
down_revision = '3ddc6b7e526f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_number', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=1500000), nullable=False),
    sa.Column('face_embedding', sa.String(length=12000), nullable=False),
    sa.Column('is_wanted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crimes')
    # ### end Alembic commands ###
